apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-database-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: fake-store
  target:
    name: k8s-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: "/db/credentials/username"
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "/db/credentials/password"
