apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: fake-store
  namespace: default
spec:
  provider:
    fake:
      data:
        - key: "/db/credentials/username"
          value: "***"
        - key: "/db/credentials/password"
          value: "***"
