apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-database-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: my-vault-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: secret/data/db-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/db-credentials
        property: password
